import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const { incidentId, format } = body;

        if (!incidentId) {
            return NextResponse.json(
                { success: false, error: 'Incident ID is required' },
                { status: 400 }
            );
        }

        // TODO: Fetch incident from database
        // For now, return mock markdown
        const mockMarkdown = `# Database Connection Pool Exhaustion

## Executive Summary
On January 15th, 2025, our primary API experienced a 47-minute outage beginning at 09:15 UTC. The incident was caused by database connection pool exhaustion.

## Timeline
- **09:15** - Monitoring alerts triggered
- **09:18** - On-call engineer acknowledged
- **09:35** - Root cause identified
- **10:02** - Incident resolved

## Root Cause
Database connection pool exhaustion due to inefficient queries.

## Action Items
| Action | Owner | Priority |
|--------|-------|----------|
| Implement connection pool alerting | DevOps | P0 |
| Add query monitoring dashboard | Platform Team | P0 |

---
*Generated by AEGIS INCIDENTS*
`;

        if (format === 'markdown' || !format) {
            return new NextResponse(mockMarkdown, {
                status: 200,
                headers: {
                    'Content-Type': 'text/markdown',
                    'Content-Disposition': 'attachment; filename="incident-postmortem.md"',
                },
            });
        }

        // For JSON response with the markdown content
        return NextResponse.json({
            success: true,
            data: {
                markdown: mockMarkdown,
                incidentId,
            },
        });

    } catch (error) {
        console.error('Error exporting incident:', error);
        return NextResponse.json(
            { success: false, error: 'Failed to export incident' },
            { status: 500 }
        );
    }
}
